[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["libxslt", "libxml2", "python312"]
aptPkgs = [
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libgdk-pixbuf2.0-0",
  "libcairo2",
  "libffi8",
  "shared-mime-info",
  "fonts-liberation"
]
